### ISSUE TITLE
deleteDatabase() crashes with memoryDatabase.

### ISSUE THREAD

**Issue by mikelehen** [indexeddbshim/IndexedDBShim#320]
Repro code:
```
const setGlobalVars = require('indexeddbshim');
global.window = global;

setGlobalVars(null, {
  memoryDatabase: ':memory:',
  checkOrigin: false,
});

const open = indexedDB.open('my_db', 1);
open.onsuccess = () => {
  console.log('DB opened...');
  const db = open.result;
  // ...

  db.close();
  console.log('Deleting...');
  indexedDB.deleteDatabase('my_db');
};
```

Result:
```
TypeError: Cannot convert undefined or null to object
indexeddbshim-node.js:2509
    at Function.keys (<anonymous>)
    at getLatestCachedWebSQLVersion (/Users/mikelehen/tmp/indexeddb-test/node_modules/indexeddbshim/dist/indexeddbshim-node.js:2509:19)
    at getLatestCachedWebSQLDB (/Users/mikelehen/tmp/indexeddb-test/node_modules/indexeddbshim/dist/indexeddbshim-node.js:2514:5)
    at cleanupDatabaseResources (/Users/mikelehen/tmp/indexeddb-test/node_modules/indexeddbshim/dist/indexeddbshim-node.js:2520:60)
    at SQLTask.sqlCallback (/Users/mikelehen/tmp/indexeddb-test/node_modules/indexeddbshim/dist/indexeddbshim-node.js:3016:33)
    at /Users/mikelehen/tmp/indexeddb-test/node_modules/websql/lib/websql/WebSQLTransaction.js:70:19
    at checkDone (/Users/mikelehen/tmp/indexeddb-test/node_modules/websql/lib/sqlite/SQLiteDatabase.js:60:7)
    at /Users/mikelehen/tmp/indexeddb-test/node_modules/websql/lib/sqlite/SQLiteDatabase.js:69:7
    at Statement.<anonymous> (/Users/mikelehen/tmp/indexeddb-test/node_modules/websql/lib/sqlite/SQLiteDatabase.js:46:5)
```

I think you need to pass `name` when calling `getLatestCachedWebSQLVersion()` here: https://github.com/axemclion/IndexedDBShim/blob/335e362fee00e40faa4e663d2bef80ccb576b177/src/IDBFactory.js#L113

**Comment by brettz9** [comment]
Thanks for the helpful report! Fixed in `master` and 3.6.2...
